### ISSUE TITLE
Error in spikely_cohort.yaml

### ISSUE THREAD

**Issue by nicoleruiz** [Yandell-Lab/spikely#1]
Line 46 needs a '#' at the beginning of the line and the indentations on lines 61 and 62 are off. 

I'm not sure if this is only meant to be an example file, but the tool ran once I made the changes.

**Comment by barrymoore** [comment]
Hi Nicole,  Thanks for the issue report and the fix!  Yes, the config is meant to be an example, but it should be a working example :)  I've committed the updates to the repo for fixing this.
